### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by bhk1019** [CarlH2019/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

https://github.com/CarlH2019/splurty/blob/9a4d360abba2a64e8c63520013da5311e77af39d/app/views/layouts/application.html.erb#L7

**Comment by CarlH2019** [comment]
consulted https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag, went with
<meta name="viewport" content="width=device-width, initial-scale=0.86, maximum-scale=3.0, minimum-scale=0.86">
